before_install: gem install bundler
language: ruby
rvm:
  - 2.5
  - 2.6
  - 2.7
gemfile:
  - Gemfile
addons:
  postgresql: "9.4"
env:
  - PGUSER=postgres
before_script:
  - psql -c 'create database message_bus_test;' -U postgres
services:
  - redis-server
  - postgresql
